Repository WolvenKit/WolvenKit, pull requests merged in 2022-10, with the labels that each got.

#933 RxApp DefaultExceptionHandler
  WolvenKit/App.xaml.cs
Labels: enhancement

#934 Fix for ImportExportViewModel Crash
  WolvenKit.App/ViewModels/Tools/ImportExportViewModel.cs
Labels: bug

#938 Continued Fix For ImportSettings Code
  WolvenKit.App/Services/IProjectManager.cs
  WolvenKit.App/ViewModels/Tools/ImportExportViewModel.cs
  WolvenKit/Views/Tools/ImportExportView.xaml.cs
Labels: bug, enhancement

#941 Rework Depot Operations
  WolvenKit.App/ViewModels/Shell/MenuBarViewModel.cs
  WolvenKit.Common/Interfaces/IModTools.cs
  WolvenKit.Core/Extensions/IEnumerableExtensions.cs
  WolvenKit.Core/Interfaces/IGameFile.cs
  WolvenKit.Modkit/RED4/Tools/MlmaskTools.cs
  WolvenKit.Modkit/RED4/Uncook.cs
  WolvenKit.RED4.Archive/Base/FileEntry.cs
  WolvenKit/App.xaml.cs
  WolvenKit/Views/Dialogs/Windows/MaterialsRepositoryDialog.xaml
  WolvenKit/Views/Dialogs/Windows/MaterialsRepositoryDialog.xaml.cs
  WolvenKit/Views/Shell/MenuBarView.xaml
  WolvenKit/Views/Shell/MenuBarView.xaml.cs
Labels: bug, enhancement

#955 Update "Open in Asset Browser" to full expand Browser to file path
  WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
  WolvenKit/Views/Tools/AssetBrowserView.xaml
  WolvenKit/Views/Tools/AssetBrowserView.xaml.cs
Labels: enhancement, GUI

#967 AssetBrowserViewModel: Browse to Folder
  WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
  WolvenKit/Views/Tools/AssetBrowserView.xaml
  WolvenKit/Views/Tools/AssetBrowserView.xaml.cs
Labels: enhancement
