Repository WolvenKit/WolvenKit, pull requests merged in 2022-03, with the labels that each got.

#710 Add libs to main directory and reference them by name and not path
  WolvenKit.Core/Compression/KrakenNative.cs
  WolvenKit.Core/Compression/OozNative.cs
  WolvenKit.Core/WolvenKit.Core.csproj
Labels: bug

#704 Add Launch Game button to main toolbar
  WolvenKit.App/Services/ISettingsManager.cs
  WolvenKit.App/Services/SettingsManager.cs
  WolvenKit.App/ViewModels/Shell/AppViewModel.cs
  WolvenKit/Views/Shell/RibbonView.xaml
  WolvenKit/Views/Shell/RibbonView.xaml.cs
Labels: enhancement

#748 LaunchCommand/LaunchOptions In Settings, Used By Launch Button (Plus Versioned Settings Support..)
  WolvenKit.App/Services/ISettingsManager.cs
  WolvenKit.App/Services/SettingsManager.cs
  WolvenKit.App/ViewModels/Shell/AppViewModel.cs
  WolvenKit.App/ViewModels/Wizards/FirstSetupWizardViewModel.cs
  WolvenKit/Views/HomePage/Pages/SettingsPageView.xaml.cs
Labels: bug, enhancement, UI/UX, GUI

#735 Added function/button to launch CP77 via Steam
  WolvenKit.App/ViewModels/Shell/AppViewModel.cs
  WolvenKit/Views/Shell/RibbonView.xaml
  WolvenKit/Views/Shell/RibbonView.xaml.cs
Labels: enhancement, GUI
