Repository WolvenKit/WolvenKit, pull requests merged in 2025-09, with the labels that each got.

#2622 fix(ImportViewModel): prevent concurrent file access errors when importing meshes/morphtargets
  WolvenKit.App/ViewModels/Importers/ImportViewModel.cs
Labels: bug

#2624 fix: image preview when format is invalid or unsupported
  WolvenKit.App/Helpers/ImageDecoder.cs
  WolvenKit.App/ViewModels/Documents/RDTTextureViewModel.cs
  WolvenKit.App/ViewModels/Tools/PropertiesViewModel.cs
  WolvenKit/Resources/Media/Images/Placeholders/Error_ImageFormat.png
  WolvenKit/WolvenKit.csproj
Labels: bug, ux/ui

#2628 feat(WelcomePageView): improve layout and responsiveness
  WolvenKit.App/ViewModels/HomePage/HomePageViewModel.cs
  WolvenKit.App/ViewModels/Shell/AppViewModel.cs
  WolvenKit/Converters/LessThanConverter.cs
  WolvenKit/Themes/App.Sizes.xaml
  WolvenKit/Views/HomePage/HomePageView.xaml
  WolvenKit/Views/HomePage/Pages/WelcomePageView.xaml
  docs/CONTRIBUTING.md
Labels: bug, ux/ui

#2644 Fix: "view" menu entries
  WolvenKit.App/ViewModels/Shell/AppViewModel.cs
  WolvenKit.App/ViewModels/Shell/MenuBarViewModel.cs
  WolvenKit.Core/WikiLinks.cs
  WolvenKit/Views/Shell/MenuBarView.xaml
  WolvenKit/Views/Shell/MenuBarView.xaml.cs
Labels: bug, ux/ui

#2679 importargs: disable garment support param by default for wepaons etc
  WolvenKit.App/ViewModels/Tools/ImportableItemViewModel.cs
Labels: enhancement

#2682 throw if bones are imported into a mesh without
  WolvenKit.Modkit/RED4/Tools/MeshTools.cs
Labels: enhancement
