Repository WolvenKit/WolvenKit, pull requests merged in 2025-01, with the labels that each got.

#2108 feat(CurveEditor): improve contrast ratio
  WolvenKit.App/ViewModels/Shell/AppViewModel.cs
  WolvenKit/Themes/App.Styles.xaml
  WolvenKit/Views/Templates/CurveEditorWindow.xaml
  WolvenKit/Views/Templates/CurveEditorWindow.xaml.cs
Labels: enhancement, ux/ui

#2109 feat(RedTree/RedType): stick buttons on the right
  WolvenKit/Views/Templates/RedTypeView.xaml
  WolvenKit/Views/Tools/RedTreeView.xaml
Labels: enhancement, ux/ui

#2112 build: bump NuGet packages
  Directory.Packages.props
  WolvenKit/Initializations.cs
Labels: bug, dependencies

#2113 fix(ProjectExplorer): scrollbar no longer showing ontop of buttons
  WolvenKit/Views/Tools/ProjectExplorerView.xaml
Labels: ux/ui

#2125 feat: improve UI/UX in RDTDataView and descendants
  WolvenKit/Views/Documents/RDTDataView.xaml
  WolvenKit/Views/Templates/RedChunkMaskEditor.xaml
  WolvenKit/Views/Templates/RedRefEditor.xaml
  WolvenKit/Views/Templates/RedRefEditor.xaml.cs
Labels: bug, enhancement, ux/ui

#2127 feat: add quick access to open curve editor
  WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
  WolvenKit/Converters/TreeViewItemTemplateSelector.cs
  WolvenKit/Views/Templates/RedCurveEditor.xaml
  WolvenKit/Views/Templates/RedCurveEditor.xaml.cs
  WolvenKit/Views/Templates/RedTypeView.xaml
  WolvenKit/Views/Tools/RedTreeView.xaml
Labels: enhancement, ux/ui

#2200 fix(LogView): improve responsiveness
  WolvenKit.App/ViewModels/Shell/AppViewModel.cs
  WolvenKit/Themes/App.Sizes.xaml
  WolvenKit/Views/Tools/LogView.xaml
  WolvenKit/Views/Tools/LogView.xaml.cs
Labels: bug, ux/ui

#2142 feature: remember open files
  WolvenKit.App/Models/ProjectManagement/CP77Mod.cs
  WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
  WolvenKit.App/Services/ISettingsManager.cs
  WolvenKit.App/Services/ProjectManager.cs
  WolvenKit.App/Services/SettingsDto.cs
  WolvenKit.App/Services/SettingsManager.cs
  WolvenKit.App/Services/WatcherService.cs
  WolvenKit.App/ViewModels/Documents/DocumentViewModel.cs
  WolvenKit.App/ViewModels/Documents/IDocumentViewModel.cs
  WolvenKit.App/ViewModels/Shell/AppViewModel.cs
  WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
  WolvenKit.sln.DotSettings
Labels: enhancement, p2

#2195 #2128 change facial animation: refresh
  WolvenKit.App/Helpers/DocumentTools.cs
  WolvenKit/Views/Dialogs/Windows/SelectFacialAnimationPathDialog.xaml
  WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
Labels: bug, p2
