Repository WolvenKit/WolvenKit, pull requests merged in 2025-10, with the labels that each got.

#2688 feat: improve UI of Scene Graph and its dialog
  WolvenKit/Views/Dialogs/SceneInputDialogView.xaml
  WolvenKit/Views/Documents/SceneGraphView.xaml
Labels: enhancement, ux/ui

#2689 fix(ProjectExplorer): font scaling in hierarchical tree and flat tree
  WolvenKit/Views/Tools/ProjectExplorerView.xaml
Labels: ux/ui

#1868 feat: generate ArchiveXL files thanks to a wizard dialog
  WolvenKit.App/Equipment_Enums.cs
  WolvenKit.App/Factories/DialogViewModelFactory.cs
  WolvenKit.App/Helpers/ArchiveXlHelper.cs
  WolvenKit.App/Helpers/Cr2WTools.cs
  WolvenKit.App/Helpers/InkatlasImageGenerator.cs
  WolvenKit.App/Helpers/ProjectResourceTools.cs
  WolvenKit.App/Helpers/YamlHelper.cs
  WolvenKit.App/Interaction/Interactions.cs
  WolvenKit.App/Services/ArchiveXlItemService.cs
  WolvenKit.App/ViewModels/Dialogs/AddArchiveXlFilesDialogViewModel.cs
  WolvenKit.App/ViewModels/Dialogs/AddItemsToStoreDialogViewModel.cs
  WolvenKit.App/ViewModels/Dialogs/NewFileViewModel.cs
  WolvenKit.App/ViewModels/Shell/AppViewModel.cs
  WolvenKit.App/ViewModels/Shell/MenuBarViewModel.cs
  WolvenKit.Core/Enums.cs
  WolvenKit.Core/WikiLinks.cs
  WolvenKit.sln.DotSettings
  WolvenKit/GenericHost.cs
  WolvenKit/Themes/App.Sizes.xaml
  WolvenKit/Themes/App.Styles.xaml
  WolvenKit/Themes/ValidationRules.xaml
  WolvenKit/ViewModels/Validators/DepotPathValidationRule.cs
  WolvenKit/ViewModels/Validators/ItemNameValidationRule.cs
  WolvenKit/Views/Controls/ValidationTextBlock.xaml
  WolvenKit/Views/Controls/ValidationTextBlock.xaml.cs
  WolvenKit/Views/Dialogs/Windows/AddArchiveXlFilesDialog.xaml
  WolvenKit/Views/Dialogs/Windows/AddArchiveXlFilesDialog.xaml.cs
  WolvenKit/Views/Dialogs/Windows/AddItemsToStoreDialog.xaml
  WolvenKit/Views/Dialogs/Windows/AddItemsToStoreDialog.xaml.cs
  WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
  WolvenKit/Views/Shell/MainView.xaml.cs
  WolvenKit/Views/Shell/MenuBarView.xaml
  WolvenKit/Views/Shell/MenuBarView.xaml.cs
Labels: enhancement

#2685 Feature: add items to atelier store / ccxl vendor
  WolvenKit.App/Helpers/ProjectResourceTools.cs
  WolvenKit.App/Helpers/YamlHelper.cs
  WolvenKit.App/Interaction/Interactions.cs
  WolvenKit.App/ViewModels/Dialogs/AddItemsToStoreDialogViewModel.cs
  WolvenKit.App/ViewModels/Shell/MenuBarViewModel.cs
  WolvenKit/Views/Dialogs/Windows/AddItemsToStoreDialog.xaml
  WolvenKit/Views/Dialogs/Windows/AddItemsToStoreDialog.xaml.cs
  WolvenKit/Views/Shell/MainView.xaml.cs
  WolvenKit/Views/Shell/MenuBarView.xaml
  WolvenKit/Views/Shell/MenuBarView.xaml.cs
Labels: enhancement
